# http://yardoc.org/guides/extending-yard/writing-handlers.html

class TestHandler < YARD::Handlers::Ruby::Base
  handles method_call(:test)

  def process
    name = statement.parameters.first.jump(:tstring_content, :ident).source
    p "IN HANDLER"
    p name
    object = YARD::CodeObjects::MethodObject.new(namespace, "test_#{name.gsub(" ", "_")}")
    register(object)
    parse_block(statement.last.last, :owner => object)

    # modify the object 
    object.dynamic = true 

    # add custom metadata to the object
    object['custom_field'] = 'Generated by Methodify'
  end
end
